### ISSUE TITLE
different user than root

### ISSUE THREAD

**Issue by MaBecker** [harmon25/node-usb-barcode-scanner#4]
Hi, 

like to run the test.js as a different user, it works fine for user  root.

user tester is member of goup plugdev

gpios@bbb:~/pbl/node_modules/node-usb-barcode-scanner/tests$ node test.js 
[ { vendorId: 1529,
    productId: 8724,
    path: '0001:0004:00',
    release: 769,
    interface: 0 } ]

Error: cannot open device with path 0001:0004:00
    at new HID (/home/gpios/pbl/node_modules/node-usb-barcode-scanner/node_modules/node-hid/index.js:24:14)
    at usbScanner.init (/home/gpios/pbl/node_modules/node-usb-barcode-scanner/usbscanner.js:47:15)
    at new usbScanner (/home/gpios/pbl/node_modules/node-usb-barcode-scanner/usbscanner.js:14:7)
    at Object.<anonymous> (/home/gpios/pbl/node_modules/node-usb-barcode-scanner/tests/test.js:11:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by MaBecker** [comment]
fixed:

vi /etc/udev/rules.d/50-hidraw.rules
KERNEL=="hidraw*", GROUP="plugdev", MODE="0660" RUN+="/bin/chgrp -R plugdev /dev/bus/usb/001"

**Comment by jitendra-khatri** [comment]
@MaBecker Is there any way to do this on Windows Machine?
