### ISSUE TITLE
 Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by deblis** [harmon25/node-usb-barcode-scanner#9]
C:\xampp\htdocs\node-barcode\node_modules\node-usb-barcode-scanner\usbscanner.js:47
        var device = new HID.HID(scanner.path);
                                        ^
I get this error. Can you helpme.

TypeError: Cannot read property 'path' of undefined
    at usbScanner.init (C:\xampp\htdocs\node-barcode\node_modules\node-usb-barcode-scanner\usbscanner.js:47:34)
    at new usbScanner (C:\xampp\htdocs\node-barcode\node_modules\node-usb-barcode-scanner\usbscanner.js:14:7)
    at Object.<anonymous> (C:\xampp\htdocs\node-barcode\app.js:15:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by safinn** [comment]
You must have no device connected with the vendor id you specified or the default `1534`. It might be best to call `getDevices()` first to get a list of vendor id's and then create the usb scanner like this `const scanner = new usbScanner({vendorId: 1534});`. 

It would be good to update the module to have a safety check for this.

**Comment by deblis** [comment]
Thanksss !!!!!!!!!!!
